### ISSUE TITLE
Relative height of bars does not increase as expected on data update

### ISSUE THREAD

**Issue by lynchjames** [Mitcheljager/svelte-tiny-linked-charts#10]
When updating chart data dynamically, the relative heights of bars do not adjust correctly unless the LinkedChart component is reloaded.

Before data update (furthest left bar is 270, furthest right bar is 191):

![image](https://github.com/Mitcheljager/svelte-tiny-linked-charts/assets/113271/cda96497-5f3a-4e34-922e-5d955a279f68)

After dynamic data update (furthest left bar is 270, furthest right bar is 396):

![image](https://github.com/Mitcheljager/svelte-tiny-linked-charts/assets/113271/d474f9be-7bb0-45ef-924b-15974a0cc71a)

After reload of component (furthest left bar is 270, furthest right bar is 396 :

![image](https://github.com/Mitcheljager/svelte-tiny-linked-charts/assets/113271/d9e1ca8a-e218-4fb3-b26f-4fa2dc866245)

**Comment by Mitcheljager** [comment]
Thanks! This should be fixed in 1.4.2 with 0db39c048c4b23451b7859927ea38d4af881a464

**Comment by lynchjames** [comment]
Confirmed as fixed for me in 1.4.2. Thanks for the quick response!
