### ISSUE TITLE
Disabling selected bar indicator

### ISSUE THREAD

**Issue by NatumanyaGuy** [Mitcheljager/svelte-tiny-linked-charts#11]
I'd love to be able to disable the indicator that wraps around the clicked bar.
How can I remove the indicator for clicked bar, or can I be able to customize my own indicator?
Thanks in Advance. Love from Uganda
![Capture](https://github.com/Mitcheljager/svelte-tiny-linked-charts/assets/66813044/53165cf4-4623-4060-8854-e0f80fe55d95)

**Comment by Mitcheljager** [comment]
This is the default focus visible state for your browser, which you can hide using CSS. In your wrapper you could do something like this:

```css
.chart :global(rect:focus-visible) {
  outline: none;
}
```

**Comment by NatumanyaGuy** [comment]
Thanks a lot. It worked.
