### ISSUE TITLE
Awesome plugin (I had issues getting it to work but fixed)

### ISSUE THREAD

**Issue by fyrineholm** [Mitcheljager/svelte-tiny-linked-charts#12]
I couldn't get this to work. Does it require svelte-kit (I'm on vanilla svelte)? Shame because the svelte-tiny-linked-charts demo looks super cool, would've loved to have it in my project. When I tried to test it, it just threw loads of untraceable errors surrounding element creation. I wish I'd had the good mind to copy them but alas I've already reverted the changes.

Edit: I looked a tiny bit more into it and it seems all of the attempts to create the circle and rect elements which are supposed to render the chart on the page failed. 

Edit 2: I got it working! c: 
It's so cool I'm so happy with this it looks so awesome and I love it thank you for making it! (Closing now)

**Comment by Mitcheljager** [comment]
Glad you got it to work! Could you explain what errors you were running into and what you did to solve them? That might help others who run into similar problems in the future.

**Comment by fyrineholm** [comment]
Yeah sorry im new to this. The fix was to uninstall some libraries. I'm sorry I can't be more helpful than that but I already removed the commits from history so I can't do an aw top sea.
