### ISSUE TITLE
"svelte-tiny-linked-charts doesn't appear to be written in CJS, but also doesn't appear to be a valid ES module"

### ISSUE THREAD

**Issue by brunobely** [Mitcheljager/svelte-tiny-linked-charts#3]
I get this message when trying to use with Vite. As far as I can tell, it still works. The full message is:

> ``` svelte-tiny-linked-charts doesn't appear to be written in CJS, but also doesn't appear to be a valid ES module (i.e. it doesn't have "type": "module" or an .mjs extension for the entry point). Please contact the package author to fix. ```

**Comment by Mitcheljager** [comment]
Fixed with https://github.com/Mitcheljager/svelte-tiny-linked-charts/commit/f0930d051343a059250180c35ecf0fdd9d57bc11
