### ISSUE TITLE
Minimum bar height to make it visible that value is not zero?

### ISSUE THREAD

**Issue by bluepuma77** [Mitcheljager/svelte-tiny-linked-charts#4]
Thanks for this tiny library! 😃 

Is there a way I can tell `svelte-tiny-linked-charts` to draw at least a pixel for the bar, so it's visible something is there?

<img width="406" alt="svelte-tiny-linked-charts_marker" src="https://user-images.githubusercontent.com/5221187/234104592-eced5545-aac4-4992-88d9-a4094ac225d8.png">

With high fluctuation, sometimes very low numbers are not shown, you can't see that something happened.

It would be great to have something like `barMinHeight` when the value is > 0.

Just an additional thought, fully optional: if you want to be more flexible than `>0`, an additional `barMinHeightValue=1` could be used to trigger `barMinHeight` to be drawn.

**Comment by Mitcheljager** [comment]
Hi! It's not currently possible but I will see what I can do!

**Comment by Mitcheljager** [comment]
Fixed with 7ca2436. You can use the `barMinHeight` property to specify a minimum height in pixels.

**Comment by bluepuma77** [comment]
That is really awesome, thank you! :tada:

**Comment by bluepuma77** [comment]
@Mitcheljager: minBar is even showing when the value is absolutely zero. 

<img width="355" alt="svelte-tiny-linked-charts_zero" src="https://user-images.githubusercontent.com/5221187/234206295-f672bdf8-8f42-4771-8272-bf119b6a3d7b.png">

The idea was to show the `barMinHeight` when value is > 0.

Zero: show nothing. Larger zero: make sure to show something.

**Comment by bluepuma77** [comment]
By the way: typo "Mimumum" in the docs

**Comment by Mitcheljager** [comment]
@bluepuma77 I see what you mean, I didn't quite understand that from your original issue. I will see what I can do!

**Comment by Mitcheljager** [comment]
@bluepuma77 I've added a new `hideBarBelow` prop, which when set to 1 will hide bars with 0 as a value. However I also fixed your question in a different way. Bars will now always round up, so your original set up might now work even without the 2 new props.

**Comment by bluepuma77** [comment]
@Mitcheljager Thanks you soo much! Sounds very promising. 

Can you update https://www.npmjs.com/package/svelte-tiny-linked-charts ? Thanks again 🥳
