### ISSUE TITLE
Please publish typescript types 

### ISSUE THREAD

**Issue by reubenfirmin** [Mitcheljager/svelte-tiny-linked-charts#7]
Thanks for the library. Would it be possible for you to publish typescript types for it?

**Comment by Mitcheljager** [comment]
With 96f67a167c9ec6b7e937f40967dae8d3537768ee the entire project has moved to Svelte 4 and with that the default way of creating packages for Svelte. This also means types are now generated automatically. I don't use Typescript myself, so please let me know if it all works as expected.
