### ISSUE TITLE
grow/height work differently for line vs bar charts

### ISSUE THREAD

**Issue by reubenfirmin** [Mitcheljager/svelte-tiny-linked-charts#8]
```<LinkedChart height="100" grow="true" data={data} type="line" lineColor="blue"></LinkedChart>```

vs

```
<LinkedChart height="100" grow="true" data={data} type="bar"></LinkedChart>
```

have very different behavior. I'd expect that the charts occupy the same render area, whether they are line or bar.

**Comment by Mitcheljager** [comment]
This should be fixed with 136994823efde48a365ce0c31765b87416928e4f. Additionally there now is a `preserveAspectRatio` prop that when set to true preserves the aspect ratio of the svg, meaning line charts will look more correct.
