### ISSUE TITLE
Please export classList parameters to allow theming

### ISSUE THREAD

**Issue by reubenfirmin** [Mitcheljager/svelte-tiny-linked-charts#9]
Please provide classList parameters on the render container and on the chart elements themselves, so that e.g. tailwind classes can be passed into theme the background and foreground of the charts.

**Comment by Mitcheljager** [comment]
`$$restProps` is now spread on the svg, meaning you can simply add `class="tailwind utility-class"` to the LinkedChart component

**Comment by nalin** [comment]
This doesn't work for me. Can you give me an example of the properties that we can use to style the charts? For example I've tried putting a class on the LinkedChart component and then experimented with setting the fill and stroke properties but no luck.

**Comment by nalin** [comment]
I was able to workaround by using `fill` property directly on the component.
